### ISSUE TITLE
Previously correct OTP is invalidated when a wrong otp is received

### ISSUE THREAD

**Issue by luizfonseca** [stas/otp-jwt#5]
Hi 👋 

First of all, amazing work in this library! Simple & straight to the point.

I was wondering why is this the default behavior for the `verify_otp` method:

https://github.com/stas/otp-jwt/blob/1a76c1d81421aa542d03ad6ab8f7a3f1c374277a/lib/otp/active_record.rb#L42

Testing locally, if I send an incorrect OTP, the previous one gets invalidated and the users has to generate another one.

Is this the behavior or am I missing some configuration?

**Comment by stas** [comment]
Obrigado Luiz :blush: 

The reason we need to increment the counter every time is because otherwise anybody could brute-force the code. We could improve the behavior by having a min/max retries, but I don't find it worth it, simply because the OTP is sent either through the email or SMS, so any typo is either a human error or somebody is trying to do :fish:y things...

A simple work-around would be to inform the user they submitted a wrong OTP and ask them if they want to receive a new OTP (and the front-end app will re-submit the previous OTP request). This way they are just one click away from receiving the second correct OTP.

Please let me know if this makes sense.

**Comment by luizfonseca** [comment]
Hey @stas 

Sounds reasonable to me. I wanted to understand the design choices and I agree with you. I will probably just clarify to the users what happens when they type a wrong code 👍 

Thanks for the support so far!
