### ISSUE TITLE
Fix docs

### ISSUE THREAD

**Issue by tamoyal** [stas/otp-jwt#7]
I think `include OTP::ActiveRecord` should be this `include OTP::JWT::ActiveRecord`.

**Comment by stas** [comment]
@tamoyal there are two modules, one which is related to the OTP, when you need just the OTP and you have your own implementation around it. And the other one which is related to the JWT support for the models.

Looking back, I should probably name it actually just `JWT::ActiveRecord` since it has nothing to do with OTP :see_no_evil: 
https://github.com/stas/otp-jwt/blob/master/lib/otp/jwt/active_record.rb

Let me know if this helped. :bow:
